### ISSUE TITLE
Это мусор какой-то а не проект.

### ISSUE THREAD

**Issue by javadev** [KasperskyLab/ForensicsTools#1]
Commits on Jan 25, 2018
first commit

@IndecentResponse
IndecentResponse committed on 25 Jan
 
first commit

@LolekAndBolek
LolekAndBolek committed on 25 Jan
 
first commit

@LolekAndBolek
LolekAndBolek committed on 25 Jan

Похоже кто-то учился пользоваться гитом.

**Comment by govnokodd** [comment]
I'm here
